rails g model Dict::LoadPort
rails g model Dict::MetalCabinet
rails g model Dict::PayWay
rails g model Dict::Port
rails g model Dict::ProcessType
rails g model Dict::ReceiptType
rails g model Dict::TaxKind
rails g model Dict::TaxMode
rails g model Dict::TradeMode
rails g model Dict::TransportMode
rails g model Dict::Truck
rails g model Dict::Usage
rails g model Dict::WrapType