require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Dict::CustomsController do

  # This should return the minimal set of attributes required to create a valid
  # Dict::Custom. As you add validations to Dict::Custom, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Dict::CustomsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dict_customs as @dict_customs" do
      custom = Dict::Custom.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dict_customs).should eq([custom])
    end
  end

  describe "GET show" do
    it "assigns the requested custom as @custom" do
      custom = Dict::Custom.create! valid_attributes
      get :show, {:id => custom.to_param}, valid_session
      assigns(:custom).should eq(custom)
    end
  end

  describe "GET new" do
    it "assigns a new custom as @custom" do
      get :new, {}, valid_session
      assigns(:custom).should be_a_new(Dict::Custom)
    end
  end

  describe "GET edit" do
    it "assigns the requested custom as @custom" do
      custom = Dict::Custom.create! valid_attributes
      get :edit, {:id => custom.to_param}, valid_session
      assigns(:custom).should eq(custom)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dict::Custom" do
        expect {
          post :create, {:custom => valid_attributes}, valid_session
        }.to change(Dict::Custom, :count).by(1)
      end

      it "assigns a newly created custom as @custom" do
        post :create, {:custom => valid_attributes}, valid_session
        assigns(:custom).should be_a(Dict::Custom)
        assigns(:custom).should be_persisted
      end

      it "redirects to the created custom" do
        post :create, {:custom => valid_attributes}, valid_session
        response.should redirect_to(Dict::Custom.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved custom as @custom" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dict::Custom.any_instance.stub(:save).and_return(false)
        post :create, {:custom => {}}, valid_session
        assigns(:custom).should be_a_new(Dict::Custom)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dict::Custom.any_instance.stub(:save).and_return(false)
        post :create, {:custom => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested custom" do
        custom = Dict::Custom.create! valid_attributes
        # Assuming there are no other dict_customs in the database, this
        # specifies that the Dict::Custom created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dict::Custom.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => custom.to_param, :custom => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested custom as @custom" do
        custom = Dict::Custom.create! valid_attributes
        put :update, {:id => custom.to_param, :custom => valid_attributes}, valid_session
        assigns(:custom).should eq(custom)
      end

      it "redirects to the custom" do
        custom = Dict::Custom.create! valid_attributes
        put :update, {:id => custom.to_param, :custom => valid_attributes}, valid_session
        response.should redirect_to(custom)
      end
    end

    describe "with invalid params" do
      it "assigns the custom as @custom" do
        custom = Dict::Custom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dict::Custom.any_instance.stub(:save).and_return(false)
        put :update, {:id => custom.to_param, :custom => {}}, valid_session
        assigns(:custom).should eq(custom)
      end

      it "re-renders the 'edit' template" do
        custom = Dict::Custom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dict::Custom.any_instance.stub(:save).and_return(false)
        put :update, {:id => custom.to_param, :custom => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested custom" do
      custom = Dict::Custom.create! valid_attributes
      expect {
        delete :destroy, {:id => custom.to_param}, valid_session
      }.to change(Dict::Custom, :count).by(-1)
    end

    it "redirects to the dict_customs list" do
      custom = Dict::Custom.create! valid_attributes
      delete :destroy, {:id => custom.to_param}, valid_session
      response.should redirect_to(dict_customs_url)
    end
  end

end
