# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContractConsumptionsController do

  # This should return the minimal set of attributes required to create a valid
  # ContractConsumption. As you add validations to ContractConsumption, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContractConsumptionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all contract_consumptions as @contract_consumptions" do
      contract_consumption = ContractConsumption.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contract_consumptions).should eq([contract_consumption])
    end
  end

  describe "GET show" do
    it "assigns the requested contract_consumption as @contract_consumption" do
      contract_consumption = ContractConsumption.create! valid_attributes
      get :show, {:id => contract_consumption.to_param}, valid_session
      assigns(:contract_consumption).should eq(contract_consumption)
    end
  end

  describe "GET new" do
    it "assigns a new contract_consumption as @contract_consumption" do
      get :new, {}, valid_session
      assigns(:contract_consumption).should be_a_new(ContractConsumption)
    end
  end

  describe "GET edit" do
    it "assigns the requested contract_consumption as @contract_consumption" do
      contract_consumption = ContractConsumption.create! valid_attributes
      get :edit, {:id => contract_consumption.to_param}, valid_session
      assigns(:contract_consumption).should eq(contract_consumption)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContractConsumption" do
        expect {
          post :create, {:contract_consumption => valid_attributes}, valid_session
        }.to change(ContractConsumption, :count).by(1)
      end

      it "assigns a newly created contract_consumption as @contract_consumption" do
        post :create, {:contract_consumption => valid_attributes}, valid_session
        assigns(:contract_consumption).should be_a(ContractConsumption)
        assigns(:contract_consumption).should be_persisted
      end

      it "redirects to the created contract_consumption" do
        post :create, {:contract_consumption => valid_attributes}, valid_session
        response.should redirect_to(ContractConsumption.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contract_consumption as @contract_consumption" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContractConsumption.any_instance.stub(:save).and_return(false)
        post :create, {:contract_consumption => {}}, valid_session
        assigns(:contract_consumption).should be_a_new(ContractConsumption)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContractConsumption.any_instance.stub(:save).and_return(false)
        post :create, {:contract_consumption => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contract_consumption" do
        contract_consumption = ContractConsumption.create! valid_attributes
        # Assuming there are no other contract_consumptions in the database, this
        # specifies that the ContractConsumption created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContractConsumption.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => contract_consumption.to_param, :contract_consumption => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested contract_consumption as @contract_consumption" do
        contract_consumption = ContractConsumption.create! valid_attributes
        put :update, {:id => contract_consumption.to_param, :contract_consumption => valid_attributes}, valid_session
        assigns(:contract_consumption).should eq(contract_consumption)
      end

      it "redirects to the contract_consumption" do
        contract_consumption = ContractConsumption.create! valid_attributes
        put :update, {:id => contract_consumption.to_param, :contract_consumption => valid_attributes}, valid_session
        response.should redirect_to(contract_consumption)
      end
    end

    describe "with invalid params" do
      it "assigns the contract_consumption as @contract_consumption" do
        contract_consumption = ContractConsumption.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContractConsumption.any_instance.stub(:save).and_return(false)
        put :update, {:id => contract_consumption.to_param, :contract_consumption => {}}, valid_session
        assigns(:contract_consumption).should eq(contract_consumption)
      end

      it "re-renders the 'edit' template" do
        contract_consumption = ContractConsumption.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContractConsumption.any_instance.stub(:save).and_return(false)
        put :update, {:id => contract_consumption.to_param, :contract_consumption => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contract_consumption" do
      contract_consumption = ContractConsumption.create! valid_attributes
      expect {
        delete :destroy, {:id => contract_consumption.to_param}, valid_session
      }.to change(ContractConsumption, :count).by(-1)
    end

    it "redirects to the contract_consumptions list" do
      contract_consumption = ContractConsumption.create! valid_attributes
      delete :destroy, {:id => contract_consumption.to_param}, valid_session
      response.should redirect_to(contract_consumptions_url)
    end
  end

end
