# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContractProductsController do

  # This should return the minimal set of attributes required to create a valid
  # ContractProduct. As you add validations to ContractProduct, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContractProductsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all contract_products as @contract_products" do
      contract_product = ContractProduct.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contract_products).should eq([contract_product])
    end
  end

  describe "GET show" do
    it "assigns the requested contract_product as @contract_product" do
      contract_product = ContractProduct.create! valid_attributes
      get :show, {:id => contract_product.to_param}, valid_session
      assigns(:contract_product).should eq(contract_product)
    end
  end

  describe "GET new" do
    it "assigns a new contract_product as @contract_product" do
      get :new, {}, valid_session
      assigns(:contract_product).should be_a_new(ContractProduct)
    end
  end

  describe "GET edit" do
    it "assigns the requested contract_product as @contract_product" do
      contract_product = ContractProduct.create! valid_attributes
      get :edit, {:id => contract_product.to_param}, valid_session
      assigns(:contract_product).should eq(contract_product)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContractProduct" do
        expect {
          post :create, {:contract_product => valid_attributes}, valid_session
        }.to change(ContractProduct, :count).by(1)
      end

      it "assigns a newly created contract_product as @contract_product" do
        post :create, {:contract_product => valid_attributes}, valid_session
        assigns(:contract_product).should be_a(ContractProduct)
        assigns(:contract_product).should be_persisted
      end

      it "redirects to the created contract_product" do
        post :create, {:contract_product => valid_attributes}, valid_session
        response.should redirect_to(ContractProduct.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contract_product as @contract_product" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContractProduct.any_instance.stub(:save).and_return(false)
        post :create, {:contract_product => {}}, valid_session
        assigns(:contract_product).should be_a_new(ContractProduct)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContractProduct.any_instance.stub(:save).and_return(false)
        post :create, {:contract_product => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contract_product" do
        contract_product = ContractProduct.create! valid_attributes
        # Assuming there are no other contract_products in the database, this
        # specifies that the ContractProduct created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContractProduct.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => contract_product.to_param, :contract_product => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested contract_product as @contract_product" do
        contract_product = ContractProduct.create! valid_attributes
        put :update, {:id => contract_product.to_param, :contract_product => valid_attributes}, valid_session
        assigns(:contract_product).should eq(contract_product)
      end

      it "redirects to the contract_product" do
        contract_product = ContractProduct.create! valid_attributes
        put :update, {:id => contract_product.to_param, :contract_product => valid_attributes}, valid_session
        response.should redirect_to(contract_product)
      end
    end

    describe "with invalid params" do
      it "assigns the contract_product as @contract_product" do
        contract_product = ContractProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContractProduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => contract_product.to_param, :contract_product => {}}, valid_session
        assigns(:contract_product).should eq(contract_product)
      end

      it "re-renders the 'edit' template" do
        contract_product = ContractProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContractProduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => contract_product.to_param, :contract_product => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contract_product" do
      contract_product = ContractProduct.create! valid_attributes
      expect {
        delete :destroy, {:id => contract_product.to_param}, valid_session
      }.to change(ContractProduct, :count).by(-1)
    end

    it "redirects to the contract_products list" do
      contract_product = ContractProduct.create! valid_attributes
      delete :destroy, {:id => contract_product.to_param}, valid_session
      response.should redirect_to(contract_products_url)
    end
  end

end
