# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContractMaterialsController do

  # This should return the minimal set of attributes required to create a valid
  # ContractMaterial. As you add validations to ContractMaterial, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContractMaterialsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all contract_materials as @contract_materials" do
      contract_material = ContractMaterial.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contract_materials).should eq([contract_material])
    end
  end

  describe "GET show" do
    it "assigns the requested contract_material as @contract_material" do
      contract_material = ContractMaterial.create! valid_attributes
      get :show, {:id => contract_material.to_param}, valid_session
      assigns(:contract_material).should eq(contract_material)
    end
  end

  describe "GET new" do
    it "assigns a new contract_material as @contract_material" do
      get :new, {}, valid_session
      assigns(:contract_material).should be_a_new(ContractMaterial)
    end
  end

  describe "GET edit" do
    it "assigns the requested contract_material as @contract_material" do
      contract_material = ContractMaterial.create! valid_attributes
      get :edit, {:id => contract_material.to_param}, valid_session
      assigns(:contract_material).should eq(contract_material)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContractMaterial" do
        expect {
          post :create, {:contract_material => valid_attributes}, valid_session
        }.to change(ContractMaterial, :count).by(1)
      end

      it "assigns a newly created contract_material as @contract_material" do
        post :create, {:contract_material => valid_attributes}, valid_session
        assigns(:contract_material).should be_a(ContractMaterial)
        assigns(:contract_material).should be_persisted
      end

      it "redirects to the created contract_material" do
        post :create, {:contract_material => valid_attributes}, valid_session
        response.should redirect_to(ContractMaterial.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contract_material as @contract_material" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContractMaterial.any_instance.stub(:save).and_return(false)
        post :create, {:contract_material => {}}, valid_session
        assigns(:contract_material).should be_a_new(ContractMaterial)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContractMaterial.any_instance.stub(:save).and_return(false)
        post :create, {:contract_material => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contract_material" do
        contract_material = ContractMaterial.create! valid_attributes
        # Assuming there are no other contract_materials in the database, this
        # specifies that the ContractMaterial created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContractMaterial.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => contract_material.to_param, :contract_material => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested contract_material as @contract_material" do
        contract_material = ContractMaterial.create! valid_attributes
        put :update, {:id => contract_material.to_param, :contract_material => valid_attributes}, valid_session
        assigns(:contract_material).should eq(contract_material)
      end

      it "redirects to the contract_material" do
        contract_material = ContractMaterial.create! valid_attributes
        put :update, {:id => contract_material.to_param, :contract_material => valid_attributes}, valid_session
        response.should redirect_to(contract_material)
      end
    end

    describe "with invalid params" do
      it "assigns the contract_material as @contract_material" do
        contract_material = ContractMaterial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContractMaterial.any_instance.stub(:save).and_return(false)
        put :update, {:id => contract_material.to_param, :contract_material => {}}, valid_session
        assigns(:contract_material).should eq(contract_material)
      end

      it "re-renders the 'edit' template" do
        contract_material = ContractMaterial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContractMaterial.any_instance.stub(:save).and_return(false)
        put :update, {:id => contract_material.to_param, :contract_material => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contract_material" do
      contract_material = ContractMaterial.create! valid_attributes
      expect {
        delete :destroy, {:id => contract_material.to_param}, valid_session
      }.to change(ContractMaterial, :count).by(-1)
    end

    it "redirects to the contract_materials list" do
      contract_material = ContractMaterial.create! valid_attributes
      delete :destroy, {:id => contract_material.to_param}, valid_session
      response.should redirect_to(contract_materials_url)
    end
  end

end
