require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeclarationPackingsController do

  # This should return the minimal set of attributes required to create a valid
  # DeclarationPacking. As you add validations to DeclarationPacking, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeclarationPackingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all declaration_packings as @declaration_packings" do
      declaration_packing = DeclarationPacking.create! valid_attributes
      get :index, {}, valid_session
      assigns(:declaration_packings).should eq([declaration_packing])
    end
  end

  describe "GET show" do
    it "assigns the requested declaration_packing as @declaration_packing" do
      declaration_packing = DeclarationPacking.create! valid_attributes
      get :show, {:id => declaration_packing.to_param}, valid_session
      assigns(:declaration_packing).should eq(declaration_packing)
    end
  end

  describe "GET new" do
    it "assigns a new declaration_packing as @declaration_packing" do
      get :new, {}, valid_session
      assigns(:declaration_packing).should be_a_new(DeclarationPacking)
    end
  end

  describe "GET edit" do
    it "assigns the requested declaration_packing as @declaration_packing" do
      declaration_packing = DeclarationPacking.create! valid_attributes
      get :edit, {:id => declaration_packing.to_param}, valid_session
      assigns(:declaration_packing).should eq(declaration_packing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeclarationPacking" do
        expect {
          post :create, {:declaration_packing => valid_attributes}, valid_session
        }.to change(DeclarationPacking, :count).by(1)
      end

      it "assigns a newly created declaration_packing as @declaration_packing" do
        post :create, {:declaration_packing => valid_attributes}, valid_session
        assigns(:declaration_packing).should be_a(DeclarationPacking)
        assigns(:declaration_packing).should be_persisted
      end

      it "redirects to the created declaration_packing" do
        post :create, {:declaration_packing => valid_attributes}, valid_session
        response.should redirect_to(DeclarationPacking.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved declaration_packing as @declaration_packing" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeclarationPacking.any_instance.stub(:save).and_return(false)
        post :create, {:declaration_packing => {}}, valid_session
        assigns(:declaration_packing).should be_a_new(DeclarationPacking)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeclarationPacking.any_instance.stub(:save).and_return(false)
        post :create, {:declaration_packing => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested declaration_packing" do
        declaration_packing = DeclarationPacking.create! valid_attributes
        # Assuming there are no other declaration_packings in the database, this
        # specifies that the DeclarationPacking created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeclarationPacking.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => declaration_packing.to_param, :declaration_packing => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested declaration_packing as @declaration_packing" do
        declaration_packing = DeclarationPacking.create! valid_attributes
        put :update, {:id => declaration_packing.to_param, :declaration_packing => valid_attributes}, valid_session
        assigns(:declaration_packing).should eq(declaration_packing)
      end

      it "redirects to the declaration_packing" do
        declaration_packing = DeclarationPacking.create! valid_attributes
        put :update, {:id => declaration_packing.to_param, :declaration_packing => valid_attributes}, valid_session
        response.should redirect_to(declaration_packing)
      end
    end

    describe "with invalid params" do
      it "assigns the declaration_packing as @declaration_packing" do
        declaration_packing = DeclarationPacking.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeclarationPacking.any_instance.stub(:save).and_return(false)
        put :update, {:id => declaration_packing.to_param, :declaration_packing => {}}, valid_session
        assigns(:declaration_packing).should eq(declaration_packing)
      end

      it "re-renders the 'edit' template" do
        declaration_packing = DeclarationPacking.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeclarationPacking.any_instance.stub(:save).and_return(false)
        put :update, {:id => declaration_packing.to_param, :declaration_packing => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested declaration_packing" do
      declaration_packing = DeclarationPacking.create! valid_attributes
      expect {
        delete :destroy, {:id => declaration_packing.to_param}, valid_session
      }.to change(DeclarationPacking, :count).by(-1)
    end

    it "redirects to the declaration_packings list" do
      declaration_packing = DeclarationPacking.create! valid_attributes
      delete :destroy, {:id => declaration_packing.to_param}, valid_session
      response.should redirect_to(declaration_packings_url)
    end
  end

end
