require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeclarationCargosController do

  # This should return the minimal set of attributes required to create a valid
  # DeclarationCargo. As you add validations to DeclarationCargo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeclarationCargosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all declaration_cargos as @declaration_cargos" do
      declaration_cargo = DeclarationCargo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:declaration_cargos).should eq([declaration_cargo])
    end
  end

  describe "GET show" do
    it "assigns the requested declaration_cargo as @declaration_cargo" do
      declaration_cargo = DeclarationCargo.create! valid_attributes
      get :show, {:id => declaration_cargo.to_param}, valid_session
      assigns(:declaration_cargo).should eq(declaration_cargo)
    end
  end

  describe "GET new" do
    it "assigns a new declaration_cargo as @declaration_cargo" do
      get :new, {}, valid_session
      assigns(:declaration_cargo).should be_a_new(DeclarationCargo)
    end
  end

  describe "GET edit" do
    it "assigns the requested declaration_cargo as @declaration_cargo" do
      declaration_cargo = DeclarationCargo.create! valid_attributes
      get :edit, {:id => declaration_cargo.to_param}, valid_session
      assigns(:declaration_cargo).should eq(declaration_cargo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeclarationCargo" do
        expect {
          post :create, {:declaration_cargo => valid_attributes}, valid_session
        }.to change(DeclarationCargo, :count).by(1)
      end

      it "assigns a newly created declaration_cargo as @declaration_cargo" do
        post :create, {:declaration_cargo => valid_attributes}, valid_session
        assigns(:declaration_cargo).should be_a(DeclarationCargo)
        assigns(:declaration_cargo).should be_persisted
      end

      it "redirects to the created declaration_cargo" do
        post :create, {:declaration_cargo => valid_attributes}, valid_session
        response.should redirect_to(DeclarationCargo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved declaration_cargo as @declaration_cargo" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeclarationCargo.any_instance.stub(:save).and_return(false)
        post :create, {:declaration_cargo => {}}, valid_session
        assigns(:declaration_cargo).should be_a_new(DeclarationCargo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeclarationCargo.any_instance.stub(:save).and_return(false)
        post :create, {:declaration_cargo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested declaration_cargo" do
        declaration_cargo = DeclarationCargo.create! valid_attributes
        # Assuming there are no other declaration_cargos in the database, this
        # specifies that the DeclarationCargo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeclarationCargo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => declaration_cargo.to_param, :declaration_cargo => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested declaration_cargo as @declaration_cargo" do
        declaration_cargo = DeclarationCargo.create! valid_attributes
        put :update, {:id => declaration_cargo.to_param, :declaration_cargo => valid_attributes}, valid_session
        assigns(:declaration_cargo).should eq(declaration_cargo)
      end

      it "redirects to the declaration_cargo" do
        declaration_cargo = DeclarationCargo.create! valid_attributes
        put :update, {:id => declaration_cargo.to_param, :declaration_cargo => valid_attributes}, valid_session
        response.should redirect_to(declaration_cargo)
      end
    end

    describe "with invalid params" do
      it "assigns the declaration_cargo as @declaration_cargo" do
        declaration_cargo = DeclarationCargo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeclarationCargo.any_instance.stub(:save).and_return(false)
        put :update, {:id => declaration_cargo.to_param, :declaration_cargo => {}}, valid_session
        assigns(:declaration_cargo).should eq(declaration_cargo)
      end

      it "re-renders the 'edit' template" do
        declaration_cargo = DeclarationCargo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeclarationCargo.any_instance.stub(:save).and_return(false)
        put :update, {:id => declaration_cargo.to_param, :declaration_cargo => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested declaration_cargo" do
      declaration_cargo = DeclarationCargo.create! valid_attributes
      expect {
        delete :destroy, {:id => declaration_cargo.to_param}, valid_session
      }.to change(DeclarationCargo, :count).by(-1)
    end

    it "redirects to the declaration_cargos list" do
      declaration_cargo = DeclarationCargo.create! valid_attributes
      delete :destroy, {:id => declaration_cargo.to_param}, valid_session
      response.should redirect_to(declaration_cargos_url)
    end
  end

end
