# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ForeignEnterprisesController do

  # This should return the minimal set of attributes required to create a valid
  # ForeignEnterprise. As you add validations to ForeignEnterprise, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ForeignEnterprisesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all foreign_enterprises as @foreign_enterprises" do
      foreign_enterprise = ForeignEnterprise.create! valid_attributes
      get :index, {}, valid_session
      assigns(:foreign_enterprises).should eq([foreign_enterprise])
    end
  end

  describe "GET show" do
    it "assigns the requested foreign_enterprise as @foreign_enterprise" do
      foreign_enterprise = ForeignEnterprise.create! valid_attributes
      get :show, {:id => foreign_enterprise.to_param}, valid_session
      assigns(:foreign_enterprise).should eq(foreign_enterprise)
    end
  end

  describe "GET new" do
    it "assigns a new foreign_enterprise as @foreign_enterprise" do
      get :new, {}, valid_session
      assigns(:foreign_enterprise).should be_a_new(ForeignEnterprise)
    end
  end

  describe "GET edit" do
    it "assigns the requested foreign_enterprise as @foreign_enterprise" do
      foreign_enterprise = ForeignEnterprise.create! valid_attributes
      get :edit, {:id => foreign_enterprise.to_param}, valid_session
      assigns(:foreign_enterprise).should eq(foreign_enterprise)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ForeignEnterprise" do
        expect {
          post :create, {:foreign_enterprise => valid_attributes}, valid_session
        }.to change(ForeignEnterprise, :count).by(1)
      end

      it "assigns a newly created foreign_enterprise as @foreign_enterprise" do
        post :create, {:foreign_enterprise => valid_attributes}, valid_session
        assigns(:foreign_enterprise).should be_a(ForeignEnterprise)
        assigns(:foreign_enterprise).should be_persisted
      end

      it "redirects to the created foreign_enterprise" do
        post :create, {:foreign_enterprise => valid_attributes}, valid_session
        response.should redirect_to(ForeignEnterprise.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved foreign_enterprise as @foreign_enterprise" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForeignEnterprise.any_instance.stub(:save).and_return(false)
        post :create, {:foreign_enterprise => {}}, valid_session
        assigns(:foreign_enterprise).should be_a_new(ForeignEnterprise)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForeignEnterprise.any_instance.stub(:save).and_return(false)
        post :create, {:foreign_enterprise => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested foreign_enterprise" do
        foreign_enterprise = ForeignEnterprise.create! valid_attributes
        # Assuming there are no other foreign_enterprises in the database, this
        # specifies that the ForeignEnterprise created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ForeignEnterprise.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => foreign_enterprise.to_param, :foreign_enterprise => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested foreign_enterprise as @foreign_enterprise" do
        foreign_enterprise = ForeignEnterprise.create! valid_attributes
        put :update, {:id => foreign_enterprise.to_param, :foreign_enterprise => valid_attributes}, valid_session
        assigns(:foreign_enterprise).should eq(foreign_enterprise)
      end

      it "redirects to the foreign_enterprise" do
        foreign_enterprise = ForeignEnterprise.create! valid_attributes
        put :update, {:id => foreign_enterprise.to_param, :foreign_enterprise => valid_attributes}, valid_session
        response.should redirect_to(foreign_enterprise)
      end
    end

    describe "with invalid params" do
      it "assigns the foreign_enterprise as @foreign_enterprise" do
        foreign_enterprise = ForeignEnterprise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForeignEnterprise.any_instance.stub(:save).and_return(false)
        put :update, {:id => foreign_enterprise.to_param, :foreign_enterprise => {}}, valid_session
        assigns(:foreign_enterprise).should eq(foreign_enterprise)
      end

      it "re-renders the 'edit' template" do
        foreign_enterprise = ForeignEnterprise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForeignEnterprise.any_instance.stub(:save).and_return(false)
        put :update, {:id => foreign_enterprise.to_param, :foreign_enterprise => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested foreign_enterprise" do
      foreign_enterprise = ForeignEnterprise.create! valid_attributes
      expect {
        delete :destroy, {:id => foreign_enterprise.to_param}, valid_session
      }.to change(ForeignEnterprise, :count).by(-1)
    end

    it "redirects to the foreign_enterprises list" do
      foreign_enterprise = ForeignEnterprise.create! valid_attributes
      delete :destroy, {:id => foreign_enterprise.to_param}, valid_session
      response.should redirect_to(foreign_enterprises_url)
    end
  end

end
